name: Test Rules

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '**'

jobs:
    test-rules:
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb:10.5
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: test_user
                    MYSQL_PASSWORD: test_pass
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run bee-dev
              run: npx bee-dev &

            - name: Wait for bee-dev
              run: npx npxie await http://localhost:16337/stamps

            - name: Wait for MariaDB
              run: |
                  until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
                  echo "Waiting for MariaDB..."
                  sleep 2
                  done

            - name: Run gateway once to init database
              run: |
                  export DATABASE_PASSWORD="test_pass"
                  export DATABASE_CONFIG="{\"user\":\"test_user\",\"database\":\"test_db\"}"
                  export TEMPORARY=5
                  export BEE_API_URL=http://localhost:16337
                  node dist

            - name: Insert rules
              run: |
                  mysql -h 127.0.0.1 -u test_user -ptest_pass test_db -e "
                    INSERT INTO rules (hash, mode) VALUES
                      ('1000000000000000000000000000000000000000000000000000000000000000', 'allow'),
                      ('f000000000000000000000000000000000000000000000000000000000000000', 'deny')
                    ;
                  "

            - name: Run gateway
              run: |
                  export DATABASE_PASSWORD="test_pass"
                  export DATABASE_CONFIG="{\"user\":\"test_user\",\"database\":\"test_db\"}"
                  export TEMPORARY=5
                  export BEE_API_URL=http://localhost:16337
                  node dist > gateway.log 2>&1 < /dev/null &

            - name: Expect HTTP 302 for deny
              run: npx npxie code-equals http://localhost:3000/bzz/f000000000000000000000000000000000000000000000000000000000000000 302

            - name: Expect HTTP 200 for allow
              run: npx npxie code-equals http://localhost:3000/bzz/1000000000000000000000000000000000000000000000000000000000000000 200
